# Generated by Django 4.1.5 on 2023-01-06 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_products_description_remove_products_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='pub_date',
        ),
    ]
