# Generated by Django 4.1.5 on 2023-01-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_stock',
            field=models.IntegerField(default=0),
        ),
    ]
